language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc
      env:
        -CXX_COMPILER=g++
        -C_COMPILER=gcc
      addons:
         apt:
           sources:
            - ubuntu-toolchain-r-test
script:
- sudo /bin/sh ./getdep_linux.sh
- mkdir _out
- cd _out
- cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make
